name: RandomItemChallenge
main: MainPlugin
version: 2.0
api-version: 1.21
commands:
  roll:
    description: Roll target for next game.
    usage: /roll [difficulties]
  ready:
    description: Vote for game start.
    usage: /ready [force]
  join:
    description: Join current game.
    usage: /join
  skip:
    description: Vote to skip current game.
    usage: /skip
  surrender:
    description: Leave participation and spectate.
    usage: /surrender